---
kind: pipeline
type: docker
name: docker-build-push_frontend

platform:
  os: linux
  arch: amd64

steps:
- name: build-and-push-image
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: deepnox/docker-poetry
    tags: ${DRONE_COMMIT}.${DRONE_BUILD_NUMBER}
    dockerfile: ./Dockerfile 
    context: .

trigger:
  ref:
  - refs/tags/*
