---
kind: pipeline
type: docker
name: docker-build-push

platform:
  os: linux
  arch: amd64

steps:
  - name: send-tags-to-tags-file
    image: node
    when:
      event:
        - push
        - pull_request
    commands:
      - echo -n "$(date +'%Y%m%dT%H%M%S'), ${DRONE_COMMIT}, ${DRONE_COMMIT}.${DRONE_BUILD_NUMBER}, latest" > .tags
      
- name: build-and-push-image
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: deepnox/docker-poetry
    tags: ${DRONE_COMMIT}.${DRONE_BUILD_NUMBER}
    dockerfile: ./Dockerfile 
    context: .

trigger:
  ref:
  - refs/tags/*
